### ISSUE TITLE
Multi core? (theoretical/improvement) 

### ISSUE THREAD

**Issue by DanHolli123** [aappleby/MetroBoy#4]
If I understand correctly it is currently running on a single core/thread

Idk the intricacies of it, but as there are 8 phases they could be paired up to run on 4 threads and maybe an extra 2 for checking that they stay aligned or for how the misaligned phases interact with each other

Hypothetically of you were able to do this, it would be one heck of a feat as I imagine keeping it aligned on one that it's already difficult enough. But I think it could reap greater performance (not 4x but possibly 2x the speed as there isn't a direct correlation) 

I'm excited to see how far this ultimately goes and how well it'll be able to run in the form of logicboy

**Comment by aappleby** [comment]
The 8 phases aren't parallel, they run in sequence - A B C D E F G H A B... 

Trust me, I've spent a couple years on this and right now there's no easy way to parallelize it.

**Comment by DanHolli123** [comment]
> Trust me, I've spent a couple years on this and right now there's no easy way to parallelize it.
I didn't think so

anyways my idea was pairing it like AE,BF,CG,DH so ABCD could be processed together making calls to each other, then the same for EFGH with an extra thread or two to facilitate those calls easier

I understand that making sequential systems into parallel would be extremely difficult

I'm going to close this as it isn't likely to happen, just an idea from someone who has no clue
